package cn.xiehuangbaobao.weddingservice.invitation.dao;

import cn.xiehuangbaobao.weddingservice.invitation.dao.Guest;
import cn.xiehuangbaobao.weddingservice.invitation.dao.GuestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    int countByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    int deleteByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    int insert(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    int insertSelective(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    List<Guest> selectByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Guest record, @Param("example") GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Guest record, @Param("example") GuestExample example);
}