package cn.xiehuangbaobao.weddingservice.demo.entities;

import org.springframework.stereotype.Service;

import java.util.List;

@Service
public interface DemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dem
     *
     * @mbggenerated
     */
    int insert(Dem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dem
     *
     * @mbggenerated
     */
    List<Dem> selectAll();
}